# -*- mode: ruby -*-
# vi: set ft=ruby :


PUBLIC_ADDRESS = "10.1.2.4"
MEMORY = 2048
CPUS = 2

Vagrant.configure("2") do |config|
	config.vm.box = "projectatomic/adb"

    config.vm.provider "virtualbox" do |v, override|
        v.memory = "#{MEMORY}"
        v.cpus = "#{CPUS}"
    end

    config.vm.provider "libvirt" do |v, override|
        v.driver = "kvm"
        v.memory = "#{MEMORY}"
        v.cpus = "#{CPUS}"
    end
    
    config.vm.provision "shell", inline: <<-SHELL
        sudo yum -y install epel-release
        sudo yum -y install ansible
        sudo ansible-playbook -e public_address=#{PUBLIC_ADDRESS} /vagrant/provisioning/playbook.yml
    SHELL

    config.vm.network "private_network", ip: "#{PUBLIC_ADDRESS}"
end
